networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  dnssec-exporter:
    container_name: dnssec-exporter
    build: .
    volumes:
      - ./dnssec-checks.conf:/config/dnssec-checks.conf
    expose:
      - "9204"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - monitoring

